### ISSUE TITLE
Events with modifier won't return hasModifier as true

### ISSUE THREAD

**Issue by Karthik99999** [fourjr/brawlapi-issuetracker#10]
When using the events endpoint, an event (showdown) with a modifier won't return the `hasModifier` object as true, and won't return `modifierId` or `modifierName` either.

**Comment by Mahi-Uddin** [comment]
Is it still happening?
Please provide the JSON output.

**Comment by Mahi-Uddin** [comment]
Fixed

**Comment by Karthik99999** [comment]
Works as expected now, thanks
