### ISSUE TITLE
404 returns slow

### ISSUE THREAD

**Issue by exqlusive** [fourjr/brawlapi-issuetracker#13]
Not sure if this is a continual issue. But I am experiencing a slow reply when a user or club has not been found.

It takes > 5 seconds and up to 20-ish seconds to return a 404.

**Comment by exqlusive** [comment]
Postman is able to return a 404. My script times out automatically after 20 seconds and returns an error.

**Comment by fourjr** [comment]
What tag took 20 seconds?

**Comment by fourjr** [comment]
This is the nature of 404. We have to wait for a nonresponse by the game to know that it is a 404. Since you are unwilling to provide more information about the request, this is as much information as I can tell you.
