### ISSUE TITLE
Misc wrong data

### ISSUE THREAD

**Issue by SharpBit** [fourjr/brawlapi-issuetracker#3]
![image](https://user-images.githubusercontent.com/31069084/53537237-44503e80-3ad7-11e9-90bf-59405b998725.png)

**Comment by fourjr** [comment]
Just worked for me?
![image](https://user-images.githubusercontent.com/28086837/53633256-f0b63000-3c51-11e9-9b3f-c967479ada21.png)

**Comment by fourjr** [comment]
Managed to find the cause of issue

**Comment by SharpBit** [comment]
response:

```
{
  "timeUntilSeasonEndInSeconds": -21,
  "timeUntilSeasonEnd": "2019-03-02T02:00:00.000Z",
  "timeUntilShopResetInSeconds": 3,
  "timeUntilShopReset": "2019-03-02T02:00:00.000Z",
  "serverDateYear": 1,
  "serverDateDayOfYear": 1
}
```

**Comment by fourjr** [comment]
Resolved
