### ISSUE TITLE
Events endpoint returns "Gem Grab" for "Siege"

### ISSUE THREAD

**Issue by FrankMartensBV** [fourjr/brawlapi-issuetracker#6]
Should return gameMode: "Siege", current map is "Nuts & Bolts". endTime is correct.

{
slot: 4,
slotName: "Special Events",
startTimeInSeconds: null,
startTime: null,
endTimeInSeconds: 80931,
endTime: "2019-03-10T14:00:00.000Z",
freeKeys: 10,
mapId: 1500099,
mapName: "Stone Fort",
mapImageUrl: "https://fourjr.github.io/bs-assets/map_images/1500099.png",
gameMode: "Gem Grab",
hasModifier: false,
modifierId: null,
modifierName: null
},

**Comment by fourjr** [comment]
Resolved

**Comment by fourjr** [comment]
API, bs-data and bs-assets have been updated
